### ISSUE TITLE
Partial diffusion: potential bug or misconception

### ISSUE THREAD

**Issue by Alexander-the-Evil** [RosettaCommons/foundry#133]
Hi!
I have been getting pretty weird results with partial diffusion. The behavior of partial diffusion is not very intuitive to me.

Let's consider a simple example, I just want to wiggle around the structure of a PET hydrolase (PDB code 7NEI). I set up a really small noise (0.1 angstrom), I fix the sequence (no residues are put to unfixed_sequence), and I don't have anything in the structure to fix. Like this:
```
{
    "7nei": {
        "input": "./7nei_A.pdb",
        "partial_t": 0.1,
        "select_fixed_atoms": false,
        "select_unfixed_sequence": false
    }
}

```
So, what do I expect to see in the trajectory? As it is partial diffusion, I expect the process to be initialized not from a gaussian cloud of points, but from noized input positions of the atoms. This is, however, not the case at all, here is t=100 of the noised trajectory and the input structure:

<img width="1209" height="967" alt="Image" src="https://github.com/user-attachments/assets/b4925d2f-6c6d-4bb8-b851-10d2d92a74a3" />

All particles are still initialized randomly. I tested with a large partial_t of 15 angstrom, there is no difference in how the initial state looks like.

This behavior leads to a very weird outcome: by running a _partial_ diffusion with a very _small_ noise I can get a _completely different_ fold. It is even more striking given the fact that I fixed the whole sequence. It is as if the sequence and the sidechains do not influence the designable fold space at all. Is it so? Here, the result is in orange:

<img width="1209" height="967" alt="Image" src="https://github.com/user-attachments/assets/405a0472-13df-44fb-99e7-e51621edb10a" />

Then I entered my "tester" mode, and played around. For example, I fixed CA atoms of all residues. This time the initialization was almost correct -- CA atoms were initialized at their initial positions, and all other, unfixed atoms, not as a random gas. However, they were also _not_ initialized as just slightly noised input positions -- the starting structure looked rather a bit contracted. Here, spheres indicate atoms, the first figure is t=100 (noised trajectory), the second is t=1:

<img width="1209" height="967" alt="Image" src="https://github.com/user-attachments/assets/489ae6d4-2e13-4e06-8ef7-0583bcbeb595" />

<img width="1209" height="967" alt="Image" src="https://github.com/user-attachments/assets/35e61a27-3032-4a55-9606-abd64ebe589b" />

In principle, it is only _a bit_ weird, and it is much better than the behavior without fixing any atoms. But how do I get the same initialization if I indeed do not freeze anything as initially intended? By freezing the positions of CA atoms I don't get what I initially wanted - local exploration around the input structure.

Also, I find it peculiar that in denoised trajectory the positions of all atoms but CA are still denoized into a random gas for 80% of the trajectory, and these fixed CA atoms are denoised into the origin, and then just linearly "grow" from it. Seemingly, only frames 1-20 are actually sampling anything reasonable, while for 80 frames some unnecessary process is underway. It is partial diffusion, I would expect that only the stuff happening in t=1-20 would be sampled, this would align with the initial task definition better (if we forget that CA atoms should not be fixed) and save the time. Do you think there is a way to do it? I attach here the files from this "fixed-CA" run.

[test_7nei_0_model_0.cif.gz](https://github.com/user-attachments/files/24338997/test_7nei_0_model_0.cif.gz)

[test_7nei_0_noisy_model_0.cif.gz](https://github.com/user-attachments/files/24339000/test_7nei_0_noisy_model_0.cif.gz)

[test_7nei_0_denoised_model_0.cif.gz](https://github.com/user-attachments/files/24339001/test_7nei_0_denoised_model_0.cif.gz)

If I do the same, but ramp up partial_t to 15 angstroms, the initialization is still quite the same, really. So the noise level seemingly has no influence at all. Here is the noised trajectory:

[test_7nei_0_noisy_model_0.cif.gz](https://github.com/user-attachments/files/24339140/test_7nei_0_noisy_model_0.cif.gz)

If I just fix one CA atom, the result is really similar to not fixing anything. Finally, if I use partial diffusion, but fix all the atoms instead, I, predicatably, just get a static noised trajectory and the whole input model "growing" from the origin in the denoised one. Noise level has no effect here. So that also does not really do what I want. 

Could you please check if the code works as intended? I am happy to help however I can and discuss the issue in greater detail. Please reach me via aleksandr.zlobin@medizin.uni-leipzig.de 

TL;DR:
1. Not clear if changing partial_t does anything
2. Not clear why partial diffusion initializes from random gas when atoms are not fixed, and from partial_t-independent, partially noised and contracted structure when some atoms are fixed (feels really arbitrary)
3. Seemingly doing only t=1-20 aligns with the intuition for partial diffusion, is there a way to enforce only that?
4. It is possible that my understanding of what partial diffusion actually does is incorrect. If so, I would be happy to discuss how to make the description clearer in the documentation, and how to implement what I intuitively and incorrectly considered partial diffusion to be.

**Comment by akshay-chenna** [comment]
Hi,

I have seen something similar with my use case too.

```
{
    "specification": {
        "dialect": 2,
        "input": "/root/AB.pdb",
        "contig": "A1-291,/0,B1-108", # chain A is 395 aa long, I just need the first 291 aa
        "select_fixed_atoms": "A1-291",
        "select_unfixed_sequence": "B1-108",
        "is_non_loopy": true,
        "infer_ori_strategy": "hotspots",
        "select_hotspots": "A36,A48,A59,A81,A86,A89,A99",
        "partial_t": 5
    }
}
```

Essentially, the distributions of the backbone RMSDs of the generated binder (chain B) appear invariant to partial diffusion noise (other params being fixed). 

<img width="1470" height="593" alt="Image" src="https://github.com/user-attachments/assets/a8cbd5f9-dc0b-4298-a534-92f7d78686f4" />

Looking forward to your suggestions.

Thanks,

**Comment by Ubiquinone-dot** [comment]
Hello! Thank you for pointing this out - I've dug through the code a bit and found there was indeed a bug now fixed with #138. To me it seems that this also should explain the finding you've got that fixing the Calphas makes the output look similar but otherwise not, since it was just using a regular schedule with the bug (i.e. partial_t was basically being set to inf because of the bug).

Lmk if this doesn't still work for you!

**Comment by Alexander-the-Evil** [comment]
Thank you so much! This worked like a charm, my initial run specification now works as intended! I tested now a full-protein partial diffusion with partial_t 0.1, 0.5, 1.0, 3.0, and got exactly the expected results.

**Comment by akshay-chenna** [comment]
@Alexander-the-Evil could you please clarify how you've run your code? I am still facing the same issue (high RMSDs) for your use case:

<img width="1238" height="593" alt="Image" src="https://github.com/user-attachments/assets/38ab0afa-9726-40e8-8551-a86018a0da7b" />

```
{
    "7nei": {
        "input": "./7nei_A.pdb",
        "partial_t": 0.1,
        "select_fixed_atoms": false,
        "select_unfixed_sequence": false
    }
}
```


`python ~/apps/foundry/models/rfd3/src/rfd3/run_inference.py ckpt_path='/home/ubuntu/.foundry/checkpoints/rfd3_latest.ckpt' inputs='pd_01.json' out_dir=./out_01 n_batches=5 diffusion_batch_size=4`

Note that I have cloned and re-installed the repo after the #138 fix.

Could you let me know if I doing something obviously wrong?

Thanks,
Akshay

**Comment by Alexander-the-Evil** [comment]
@akshay-chenna 
Hi, I would first check manually in the code if the lines added by Jasper indeed are in your code. I added them manually in my case.
Then, to comment on anything obviously or not so obviously wrong, I would need to see your json and starting file, unfortunately. If you don't want to share them publicly here, let's talk 1:1 via e-mail: aleksandr.zlobin@medizin.uni-leipzig.de
Best,
Alex

**Comment by akshay-chenna** [comment]
Hello @Alexander-the-Evil,

Thank you so much for the willingness to help me out.

Yes, I have manually checked the inference_sampler.py file, it was indeed modified as per #138. I am pasting the same here:

```
            new_schedule_len = len(noise_schedule)
            if new_schedule_len > 0:
                new_max = noise_schedule.max().item()
                new_min = noise_schedule.min().item()
                ranked_logger.info(
                    f"Noise schedule: {original_schedule_len} → {new_schedule_len} steps"
                )
                ranked_logger.info(
                    f"Original range: [{original_min:.3f}, {original_max:.3f}]"
                )
                ranked_logger.info(f"Filtered range: [{new_min:.3f}, {new_max:.3f}]")
            else:
                ranked_logger.warning(
                    f"No noise schedule steps found with t <= {partial_t}!"
                )
                ranked_logger.info(
                    f"Original schedule range: [{original_min:.3f}, {original_max:.3f}]"
                )
                # Fallback to smallest available step
                noise_schedule_original = self._construct_inference_noise_schedule(
                    device=device
                )
                noise_schedule = noise_schedule_original[-1:]  # Just use the final step
                ranked_logger.info(
                    f"Using fallback: final step with t={noise_schedule[0].item():.6f}"
                )
        else:
            noise_schedule = t_hat

        return noise_schedule
```

I am attaching my files (attempted 7NEI for reproducibility.)

Thank you,
Akshay

[run_rfd3.sh](https://github.com/user-attachments/files/24389697/run_rfd3.sh)

[pd_01.json](https://github.com/user-attachments/files/24389699/pd_01.json)

[7nei_A.pdb](https://github.com/user-attachments/files/24389701/7nei_A.pdb)

**Comment by akshay-chenna** [comment]
Hello @Alexander-the-Evil , I have figured this out. All I had to do was to clear the cache and reinstall. Thanks !
