### ISSUE TITLE
KeyError: 'extra'

### ISSUE THREAD

**Issue by YueZhou-oh** [RosettaCommons/foundry#80]
When running the `all.ipynb`, I got `KeyError: 'extra'` at 
```
outputs = model.run(
    inputs=None,      # None for unconditional generation
    out_dir=None,     # None to return in memory (no file output)
    n_batches=1,      # Generate 1 batch
)
```

The error message is 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/rfd3/engine.py", line 213, in run
    design_specifications = self._multiply_specifications(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/rfd3/engine.py", line 394, in _multiply_specifications
    example_spec["extra"]["task_name"] = prefix
    ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'extra'
```

**Comment by LightMountainer** [comment]
Same Problem here.

**Comment by YueZhou-oh** [comment]
> Same Problem here.

Follow readme in RFD3, test the installation with `rfd3 design out_dir=logs/inference_outs/demo/0 inputs=models/rfd3/docs/demo.json skip_existing=False dump_trajectories=True prevalidate_inputs=True` works.

Download foundry source code and `cd` the folder.

**Comment by puddleglum56** [comment]
Think there was a bug introduced somewhere which maybe is fixed by https://github.com/RosettaCommons/foundry/commit/f1356309977ee3238c9c2013ace10805c74e837e

Unfortunately that fix doesn't seem to be in the pip package so we might need to install from source

**Comment by YueZhou-oh** [comment]
> Think there was a bug introduced somewhere which maybe is fixed by [f135630](https://github.com/RosettaCommons/foundry/commit/f1356309977ee3238c9c2013ace10805c74e837e)
> 
> Unfortunately that fix doesn't seem to be in the pip package so we might need to install from source

thanks 👍

**Comment by ardejani** [comment]
> Think there was a bug introduced somewhere which maybe is fixed by [f135630](https://github.com/RosettaCommons/foundry/commit/f1356309977ee3238c9c2013ace10805c74e837e)
> 
> Unfortunately that fix doesn't seem to be in the pip package so we might need to install from source

This issue still persists in the pip installation of v0.1.8. 
Is there any instruction on how to build from the source?

**Comment by puddleglum56** [comment]
Clone the repo and see https://github.com/RosettaCommons/foundry?tab=readme-ov-file#development
